DROP TABLE IF EXISTS alarms;

CREATE TABLE alarms (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alarmtime TEXT NOT NULL,
    alarmstate INTEGER NOT NULL DEFAULT 0,
    tag TEXT
);